export const CREATE_NEW_USER = 'CREATE_NEW_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const GET_USER = 'GET_USER';
export const GET_ALL_USER = 'GET_ALL_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';

export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_MAIN_CATEGORY = 'GET_MAIN_CATEGORY';
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';

export const GET_ALL_BRAND = 'GET_ALL_BRAND';
export const CREATE_BRAND = 'CREATE_BRAND';
export const GET_BRAND = 'GET_BRAND';
export const UPDATE_BRAND = 'UPDATE_BRAND';
export const DELETE_BRAND = 'DELETE_BRAND';

export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_SIMILAR_PRODUCT = 'GET_SIMILAR_PRODUCT';
export const GET_BEST_SELLER_PRODUCT = 'GET_BEST_SELLER_PRODUCT';
export const GET_MOST_RECENT_PRODUCT = 'GET_MOST_RECENT_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const GET_ALL_REVIEW = 'GET_ALL_REVIEW';
export const GET_REVIEW = 'GET_REVIEW';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';

export const GET_USER_WISHLIST = 'GET_USER_WISHLIST';
export const GET_USER_WISHLIST_POPULATE = 'GET_USER_WISHLIST_POPULATE';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

export const ADD_TO_CART = 'ADD_TO_CART';
export const GET_ALL_USER_CART = 'GET_ALL_USER_CART';
export const DELETE_ITEM_FROM_CART = 'DELETE_ITEM_FROM_CART';
export const UPDATE_ITEM_IN_CART = 'UPDATE_ITEM_IN_CART';

export const GET_ALL_COUPON = 'GET_ALL_COUPON';
export const CREATE_COUPON = 'CREATE_COUPON';
export const UPDATE_COUPON = 'UPDATE_COUPON';
export const DELETE_COUPON = 'DELETE_COUPON';

export const GET_ERROR = 'GET-ERROR';
