export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
export const GET_MAIN_CATEGORY = 'GET_MAIN_CATEGORY';
export const GET_SUB_CATEGORY = 'GET_SUB_CATEGORY';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const GET_CATEGORY = 'GET_CATEGORY';

export const GET_ALL_BRAND = 'GET_ALL_BRAND';
export const CREATE_BRAND = 'CREATE_BRAND';
export const GET_BRAND = 'GET_BRAND';
export const UPDATE_BRAND = 'UPDATE_BRAND';
export const DELETE_BRAND = 'DELETE_BRAND';

export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export const GET_SIMILAR_PRODUCT = 'GET_SIMILAR_PRODUCT';
export const GET_BEST_SELLER_PRODUCT = 'GET_BEST_SELLER_PRODUCT';
export const GET_MOST_RECENT_PRODUCT = 'GET_MOST_RECENT_PRODUCT';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const GET_ERROR = 'GET-ERROR';
